const express=require("express")
const mongoose=require("mongoose")
const cors=require("cors")
const app=express()

const recipeRoute=require("./routes/recipe")
const  userRouter  = require("./routes/auth")
const adminRouter=require("./routes/admin")
const user=require("./routes/user")
app.use(express.json())
app.use(cors())

app.use("/auth",userRouter)
app.use("/recipe",recipeRoute)
app .use("/admin",adminRouter)
app.use("/user",user)
mongoose.connect("mongodb+srv://luffy97780:KWTorqZH268D3otV@cluster0.ij0boyo.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0")
app. listen(3001,()=>console.log("server running on port 3001"))